version: '3.8'
services:
  www:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:80
    volumes:
      - ./php:/var/www/html/
    links:
      - mysql:localhost
  mysql:
    image: mysql:8.0.22
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 'test'
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.0.0
    links:
      - mysql:db
    ports:
      - 8081:80